name: build theme css and upload
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - name: build
      run: |
        npm ci
        npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: boilerplate.css
        path: ./build/boilerplate.css
